# Generated by Django 2.1.5 on 2019-02-17 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20190204_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='slug',
            field=models.SlugField(default='x'),
            preserve_default=False,
        ),
    ]
