# Generated by Django 2.1.7 on 2019-02-18 22:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_gallery_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='file',
            new_name='image_file',
        ),
        migrations.AddField(
            model_name='image',
            name='exif',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
