# Generated by Django 2.1.7 on 2019-02-18 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20190218_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.FileField(max_length=1000, upload_to=''),
        ),
    ]
