# Generated by Django 2.1.7 on 2019-02-19 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_auto_20190219_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='image',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
