# Generated by Django 2.1.7 on 2019-03-10 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_image_thumbnail_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['datetime', 'title', 'image_file']},
        ),
        migrations.AlterField(
            model_name='gallery',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
