# Generated by Django 2.1.7 on 2019-03-13 20:40

from django.conf import settings
from django.db import migrations


def image_file_to_image_url(apps, schema_editor):
    Image = apps.get_model('gallery', 'Image')

    for image in Image.objects.all():
        image.image_url = f"{settings.MEDIA_URL}{image.image_file}"
        image.save()


def image_url_to_image_file(apps, schema_editor):
    Image = apps.get_model('gallery', 'Image')

    # Since I'm lazy and am probably never gonna hit this corner case
    # I'm just gonna bypass it and get shouted at if I do
    if Image.objects.exclude(image_url__icontains=".jpg").exists():
        print("ERROR! Some images are not JPG. OOooOOOPS lazy me.")
        raise NotImplementedError(
            "ERROR! Some images are not JPG. OOooOOOPS lazy me.")

    for image in Image.objects.all():
        image.image_file = image.image_url.replace(settings.MEDIA_URL, "")
        image.thumbnail_file = image.image_url.replace(
            settings.MEDIA_URL, "").replace(".jpg", "_thumb.jpg")
        image.save()


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_image_image_url'),
    ]

    operations = [
        migrations.RunPython(image_file_to_image_url, image_url_to_image_file),
    ]
