# Generated by Django 2.1.7 on 2019-04-04 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0012_auto_20190313_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='thumbnail_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='gallery.Image'),
        ),
    ]
