# Generated by Django 2.2 on 2019-06-12 14:01

import apps.gallery.validators
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0014_image_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='sizes',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, validators=[apps.gallery.validators.validate_image_sizes_json]),
        ),
    ]
