version: "3"

services:
  celery:
    image: sklirg/camerabag:latest
    entrypoint: "/usr/local/bin/python"
    command: "/usr/local/bin/celery -A bag worker -l info"
    environment:
      - DATABASE_URL
      - CB_CELERY_BROKER
      - CB_CELERY_EAGER
      - CB_S3_BUCKET
    volumes:
      - /home/sklirg/.aws:/root/.aws
  django:
    image: sklirg/camerabag:latest
    environment:
      - DATABASE_URL
      - CB_CELERY_BROKER
      - CB_CELERY_EAGER
      - CB_SECRET_KEY
      - CB_S3_BUCKET
    volumes:
      - /home/sklirg/.aws:/root/.aws
    deploy:
      mode: replicated
      replicas: 5
    labels:
      - "traefik.frontend.passHostHeader=true"
      - "traefik.camerabag.frontend.rule=Host:camerabag.sklirg.io"
