version: "3"

services:
  django:
    image: sklirg/camerabag:latest
    volumes:
      - /media/images:/app/media
    environment:
      - DATABASE_URL
      - CB_SECRET_KEY
      - CB_S3_BUCKET
    deploy:
      mode: replicated
      replicas: 5
    labels:
      - "traefik.frontend.passHostHeader=true"
      - "traefik.camerabag.frontend.rule=Host:camerabag.sklirg.io"
  nginx:
    image: nginx:mainline-alpine
    volumes:
      - ./nginx-s3-proxy.conf:/etc/nginx/nginx.conf:ro
      - /var/www/html:/var/www/html
    labels:
      - "traefik.frontend.passHostHeader=true"
      - "traefik.images.frontend.rule=Host:images.sklirg.io"
      - "traefik.port=80"
