name: build-image

on:
  push:
    branches:
      - 'main'
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: config/prod.Dockerfile
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          push: true
          tags: ghcr.io/sklirg/camerabag:latest,ghcr.io/sklirg/camerabag:${{ github.ref_name }}
